export const GET_DEVELOPERS = 'GET_DEVELOPERS';
export const CREATE_DEVELOPER = 'CREATE_DEVELOPER';
export const UPDATE_DEVELOPER = 'UPDATE_DEVELOPER';
export const DELETE_DEVELOPER = 'DELETE_DEVELOPER';